# Site settings
title: magdalena wistuba
email: magda.wistuba@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chicago-based design, web design, design students, graphic design.

twitter_username: magplease
github_username:  manzalena

# Build settings
markdown: kramdown
